"""create clients table

Revision ID: 88e50bc51e42
Revises: f3c1d9a2b847
Create Date: 2026-05-01 18:59:53.999439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88e50bc51e42"
down_revision: Union[str, Sequence[str], None] = "f3c1d9a2b847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("companies_house_number", sa.String(length=50), nullable=True),
        sa.Column("primary_contact_name", sa.String(length=100), nullable=False),
        sa.Column("primary_contact_email", sa.String(length=255), nullable=False),
        sa.Column("primary_contact_phone", sa.String(length=30), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("headcount_at_engagement", sa.Integer(), nullable=False),
        sa.Column("current_headcount", sa.Integer(), nullable=True),
        sa.Column("business_stage", sa.String(length=50), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("assigned_operator_id", sa.UUID(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_operator_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
