"""add introducer fees application column

Revision ID: ce4337bb24a2
Revises: 6d3d24c28287
Create Date: 2026-05-05 13:31:36.741076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce4337bb24a2"
down_revision: Union[str, Sequence[str], None] = "6d3d24c28287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("introducer_fee_applicable", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "introducer_fee_applicable")
    # ### end Alembic commands ###
