"""create engagements table

Revision ID: fae51710eaac
Revises: 88e50bc51e42
Create Date: 2026-05-01 19:19:34.703283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "fae51710eaac"
down_revision: Union[str, Sequence[str], None] = "88e50bc51e42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engagements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("product", sa.String(length=50), nullable=False),
        sa.Column("engagement_date", sa.Date(), nullable=False),
        sa.Column("fee_charged", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fee_status", sa.String(length=50), nullable=False),
        sa.Column("audit_date", sa.Date(), nullable=True),
        sa.Column("report_issued_date", sa.Date(), nullable=True),
        sa.Column("audit_status", sa.String(length=50), nullable=False),
        sa.Column("overall_rag", sa.String(length=50), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("next_review_due", sa.Date(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_engagements_id"), "engagements", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_engagements_id"), table_name="engagements")
    op.drop_table("engagements")
    # ### end Alembic commands ###
