// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CancelAssessmentData,
  CancelAssessmentErrors,
  CancelAssessmentResponses,
  CloseAssessmentPhase1Data,
  CloseAssessmentPhase1Errors,
  CloseAssessmentPhase1Responses,
  CreateClientData,
  CreateClientErrors,
  CreateClientResponses,
  CreateControlTemplateData,
  CreateControlTemplateErrors,
  CreateControlTemplateResponses,
  CreateEngagementData,
  CreateEngagementErrors,
  CreateEngagementResponses,
  CreateRoleData,
  CreateRoleErrors,
  CreateRoleResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeactivateUserData,
  DeactivateUserErrors,
  DeactivateUserResponses,
  DeleteCalibrationAnchorData,
  DeleteCalibrationAnchorErrors,
  DeleteCalibrationAnchorResponses,
  DeleteClientData,
  DeleteClientErrors,
  DeleteClientResponses,
  DeleteControlTemplateData,
  DeleteControlTemplateErrors,
  DeleteControlTemplateResponses,
  DeleteEngagementData,
  DeleteEngagementErrors,
  DeleteEngagementResponses,
  DeleteRoleData,
  DeleteRoleErrors,
  DeleteRoleResponses,
  GetClientData,
  GetClientErrors,
  GetClientResponses,
  GetControlTemplateData,
  GetControlTemplateErrors,
  GetControlTemplateResponses,
  GetEngagementAssessmentData,
  GetEngagementAssessmentErrors,
  GetEngagementAssessmentResponses,
  GetEngagementData,
  GetEngagementErrors,
  GetEngagementGatesData,
  GetEngagementGatesErrors,
  GetEngagementGatesResponses,
  GetEngagementResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  ListAuditLogsData,
  ListAuditLogsErrors,
  ListAuditLogsResponses,
  ListClientsData,
  ListClientsResponses,
  ListControlTemplatesData,
  ListControlTemplatesErrors,
  ListControlTemplatesResponses,
  ListEngagementsData,
  ListEngagementsErrors,
  ListEngagementsResponses,
  ListGateChecksData,
  ListGateChecksErrors,
  ListGateChecksResponses,
  ListRolesData,
  ListRolesResponses,
  ListUsersData,
  ListUsersResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutResponses,
  RefreshData,
  RefreshResponses,
  RevokeSessionsData,
  RevokeSessionsErrors,
  RevokeSessionsResponses,
  StartAssessmentData,
  StartAssessmentErrors,
  StartAssessmentResponses,
  SubmitAssessmentPhase2Data,
  SubmitAssessmentPhase2Errors,
  SubmitAssessmentPhase2Responses,
  TotpConfirmData,
  TotpConfirmErrors,
  TotpConfirmResponses,
  TotpDisableData,
  TotpDisableResponses,
  TotpSetupData,
  TotpSetupResponses,
  TotpVerifyData,
  TotpVerifyErrors,
  TotpVerifyResponses,
  UpdateCalibrationAnchorData,
  UpdateCalibrationAnchorErrors,
  UpdateCalibrationAnchorResponses,
  UpdateClientData,
  UpdateClientErrors,
  UpdateClientResponses,
  UpdateControlTemplateData,
  UpdateControlTemplateErrors,
  UpdateControlTemplateResponses,
  UpdateEngagementData,
  UpdateEngagementErrors,
  UpdateEngagementResponses,
  UpdateRoleData,
  UpdateRoleErrors,
  UpdateRoleResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
  UpsertCalibrationAnchorData,
  UpsertCalibrationAnchorErrors,
  UpsertCalibrationAnchorResponses
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Refresh
 */
export const refresh = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshData, ThrowOnError>
) =>
  (options?.client ?? client).post<RefreshResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/refresh',
    ...options
  })

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/logout',
    ...options
  })

/**
 * Totp Setup
 */
export const totpSetup = <ThrowOnError extends boolean = false>(
  options?: Options<TotpSetupData, ThrowOnError>
) =>
  (options?.client ?? client).post<TotpSetupResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/totp/setup',
    ...options
  })

/**
 * Totp Disable
 */
export const totpDisable = <ThrowOnError extends boolean = false>(
  options?: Options<TotpDisableData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    TotpDisableResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/totp',
    ...options
  })

/**
 * Totp Verify
 */
export const totpVerify = <ThrowOnError extends boolean = false>(
  options: Options<TotpVerifyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TotpVerifyResponses,
    TotpVerifyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/totp/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Revoke Sessions
 */
export const revokeSessions = <ThrowOnError extends boolean = false>(
  options: Options<RevokeSessionsData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RevokeSessionsResponses,
    RevokeSessionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/sessions/{user_id}',
    ...options
  })

/**
 * Totp Confirm
 */
export const totpConfirm = <ThrowOnError extends boolean = false>(
  options: Options<TotpConfirmData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TotpConfirmResponses,
    TotpConfirmErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/totp/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * List Users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users',
    ...options
  })

/**
 * Create User
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Deactivate User
 */
export const deactivateUser = <ThrowOnError extends boolean = false>(
  options: Options<DeactivateUserData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeactivateUserResponses,
    DeactivateUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options
  })

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options: Options<GetUserData, ThrowOnError>
) =>
  (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/users/{user_id}',
      ...options
    }
  )

/**
 * Update User
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * List Roles
 */
export const listRoles = <ThrowOnError extends boolean = false>(
  options?: Options<ListRolesData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListRolesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles',
    ...options
  })

/**
 * Create Role
 */
export const createRole = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRoleResponses,
    CreateRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Delete Role
 */
export const deleteRole = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRoleData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRoleResponses,
    DeleteRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{role_id}',
    ...options
  })

/**
 * Update Role
 */
export const updateRole = <ThrowOnError extends boolean = false>(
  options: Options<UpdateRoleData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateRoleResponses,
    UpdateRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/roles/{role_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * List Clients
 */
export const listClients = <ThrowOnError extends boolean = false>(
  options?: Options<ListClientsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListClientsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients',
    ...options
  })

/**
 * Create Client
 */
export const createClient = <ThrowOnError extends boolean = false>(
  options: Options<CreateClientData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateClientResponses,
    CreateClientErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Delete Client
 */
export const deleteClient = <ThrowOnError extends boolean = false>(
  options: Options<DeleteClientData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteClientResponses,
    DeleteClientErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}',
    ...options
  })

/**
 * Get Client
 */
export const getClient = <ThrowOnError extends boolean = false>(
  options: Options<GetClientData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetClientResponses,
    GetClientErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}',
    ...options
  })

/**
 * Update Client
 */
export const updateClient = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClientData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateClientResponses,
    UpdateClientErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * List Engagements
 */
export const listEngagements = <ThrowOnError extends boolean = false>(
  options: Options<ListEngagementsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListEngagementsResponses,
    ListEngagementsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}/engagements',
    ...options
  })

/**
 * Create Engagement
 */
export const createEngagement = <ThrowOnError extends boolean = false>(
  options: Options<CreateEngagementData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateEngagementResponses,
    CreateEngagementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}/engagements',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Delete Engagement
 */
export const deleteEngagement = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEngagementData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteEngagementResponses,
    DeleteEngagementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}/engagements/{engagement_id}',
    ...options
  })

/**
 * Get Engagement
 */
export const getEngagement = <ThrowOnError extends boolean = false>(
  options: Options<GetEngagementData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetEngagementResponses,
    GetEngagementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}/engagements/{engagement_id}',
    ...options
  })

/**
 * Update Engagement
 */
export const updateEngagement = <ThrowOnError extends boolean = false>(
  options: Options<UpdateEngagementData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateEngagementResponses,
    UpdateEngagementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clients/{client_id}/engagements/{engagement_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * List Control Templates
 */
export const listControlTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<ListControlTemplatesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListControlTemplatesResponses,
    ListControlTemplatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/control-templates',
    ...options
  })

/**
 * Create Control Template
 */
export const createControlTemplate = <ThrowOnError extends boolean = false>(
  options: Options<CreateControlTemplateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateControlTemplateResponses,
    CreateControlTemplateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/control-templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Delete Control Template
 */
export const deleteControlTemplate = <ThrowOnError extends boolean = false>(
  options: Options<DeleteControlTemplateData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteControlTemplateResponses,
    DeleteControlTemplateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/control-templates/{template_id}',
    ...options
  })

/**
 * Get Control Template
 */
export const getControlTemplate = <ThrowOnError extends boolean = false>(
  options: Options<GetControlTemplateData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetControlTemplateResponses,
    GetControlTemplateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/control-templates/{template_id}',
    ...options
  })

/**
 * Update Control Template
 */
export const updateControlTemplate = <ThrowOnError extends boolean = false>(
  options: Options<UpdateControlTemplateData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateControlTemplateResponses,
    UpdateControlTemplateErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/control-templates/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Upsert Calibration Anchor
 */
export const upsertCalibrationAnchor = <ThrowOnError extends boolean = false>(
  options: Options<UpsertCalibrationAnchorData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpsertCalibrationAnchorResponses,
    UpsertCalibrationAnchorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/control-templates/{template_id}/calibration-anchors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Delete Calibration Anchor
 */
export const deleteCalibrationAnchor = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCalibrationAnchorData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCalibrationAnchorResponses,
    DeleteCalibrationAnchorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/calibration-anchors/{anchor_id}',
    ...options
  })

/**
 * Update Calibration Anchor
 */
export const updateCalibrationAnchor = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCalibrationAnchorData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateCalibrationAnchorResponses,
    UpdateCalibrationAnchorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/calibration-anchors/{anchor_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Get Engagement Gates
 */
export const getEngagementGates = <ThrowOnError extends boolean = false>(
  options: Options<GetEngagementGatesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetEngagementGatesResponses,
    GetEngagementGatesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/engagements/{engagement_id}/gates',
    ...options
  })

/**
 * Get Engagement Assessment
 */
export const getEngagementAssessment = <ThrowOnError extends boolean = false>(
  options: Options<GetEngagementAssessmentData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetEngagementAssessmentResponses,
    GetEngagementAssessmentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/engagements/{engagement_id}/assessment',
    ...options
  })

/**
 * Start Assessment
 */
export const startAssessment = <ThrowOnError extends boolean = false>(
  options: Options<StartAssessmentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    StartAssessmentResponses,
    StartAssessmentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/engagements/{engagement_id}/assessment/start',
    ...options
  })

/**
 * Close Phase 1
 */
export const closeAssessmentPhase1 = <ThrowOnError extends boolean = false>(
  options: Options<CloseAssessmentPhase1Data, ThrowOnError>
) =>
  (options.client ?? client).post<
    CloseAssessmentPhase1Responses,
    CloseAssessmentPhase1Errors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assessments/{assessment_id}/close-phase-1',
    ...options
  })

/**
 * Submit Phase 2
 */
export const submitAssessmentPhase2 = <ThrowOnError extends boolean = false>(
  options: Options<SubmitAssessmentPhase2Data, ThrowOnError>
) =>
  (options.client ?? client).post<
    SubmitAssessmentPhase2Responses,
    SubmitAssessmentPhase2Errors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assessments/{assessment_id}/submit-phase-2',
    ...options
  })

/**
 * Cancel Assessment
 */
export const cancelAssessment = <ThrowOnError extends boolean = false>(
  options: Options<CancelAssessmentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CancelAssessmentResponses,
    CancelAssessmentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/assessments/{assessment_id}/cancel',
    ...options
  })

/**
 * List Gate Checks
 */
export const listGateChecks = <ThrowOnError extends boolean = false>(
  options: Options<ListGateChecksData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListGateChecksResponses,
    ListGateChecksErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/engagements/{engagement_id}/gate-checks',
    ...options
  })

/**
 * List Audit Logs
 */
export const listAuditLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListAuditLogsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListAuditLogsResponses,
    ListAuditLogsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/audit-logs',
    ...options
  })
