// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:8000' | (string & {})
}

/**
 * AccessTokenResponse
 */
export type AccessTokenResponse = {
  /**
   * Accesstoken
   */
  accessToken: string
  /**
   * Tokentype
   */
  tokenType?: string
}

/**
 * AssessmentPhase
 */
export type AssessmentPhase =
  | 'NOT_STARTED'
  | 'PHASE_1_IN_PROGRESS'
  | 'PHASE_1_CLOSED'
  | 'PHASE_2_SUBMITTED'
  | 'CANCELLED'

/**
 * AssessmentRead
 */
export type AssessmentRead = {
  /**
   * Id
   */
  id: string
  /**
   * Engagementid
   */
  engagementId: string
  phase?: AssessmentPhase
  /**
   * Phase1Startedat
   */
  phase1StartedAt: string | null
  /**
   * Phase1Startedbyid
   */
  phase1StartedById: string | null
  /**
   * Phase1Closedat
   */
  phase1ClosedAt: string | null
  /**
   * Phase1Closedbyid
   */
  phase1ClosedById: string | null
  /**
   * Phase2Submittedat
   */
  phase2SubmittedAt: string | null
  /**
   * Phase2Submittedbyid
   */
  phase2SubmittedById: string | null
  /**
   * Cancelledat
   */
  cancelledAt: string | null
  /**
   * Createdat
   */
  createdAt: string
  /**
   * Updatedat
   */
  updatedAt: string
}

/**
 * AuditAction
 */
export type AuditAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'LOGIN' | 'LOGOUT'

/**
 * AuditLogPage
 */
export type AuditLogPage = {
  /**
   * Items
   */
  items: Array<AuditLogRead>
  /**
   * Total
   */
  total: number
}

/**
 * AuditLogRead
 */
export type AuditLogRead = {
  /**
   * Id
   */
  id: string
  /**
   * Actorid
   */
  actorId: string | null
  /**
   * Actorname
   */
  actorName?: string | null
  action: AuditAction
  /**
   * Event
   */
  event: string | null
  /**
   * Resourcetype
   */
  resourceType: string
  /**
   * Resourceid
   */
  resourceId: string | null
  /**
   * Ipaddress
   */
  ipAddress: string | null
  /**
   * Createdat
   */
  createdAt: string
  meta: AuditMeta
}

/**
 * AuditMeta
 */
export type AuditMeta = {
  /**
   * Before
   */
  before?: {
    [key: string]: unknown
  } | null
  /**
   * After
   */
  after?: {
    [key: string]: unknown
  } | null
}

/**
 * AuditStatus
 */
export type AuditStatus =
  | 'SCHEDULED'
  | 'PHASE_1_COMPLETE'
  | 'PHASE_2_COMPLETE'
  | 'REPORT_ISSUED'

/**
 * BusinessStage
 */
export type BusinessStage = 'PRE_HIRE' | 'EARLY' | 'GROWTH' | 'ESTABLISHED'

/**
 * CalibrationAnchorCreate
 */
export type CalibrationAnchorCreate = {
  ragLevel: RagLevel
  /**
   * Description
   */
  description: string
  /**
   * Severityhint
   */
  severityHint?: number | null
}

/**
 * CalibrationAnchorRead
 */
export type CalibrationAnchorRead = {
  /**
   * Id
   */
  id: string
  /**
   * Controltemplateid
   */
  controlTemplateId: string
  ragLevel: RagLevel
  /**
   * Description
   */
  description: string
  /**
   * Severityhint
   */
  severityHint: number | null
  /**
   * Createdat
   */
  createdAt: string
  /**
   * Updatedat
   */
  updatedAt: string
}

/**
 * CalibrationAnchorUpdate
 */
export type CalibrationAnchorUpdate = {
  ragLevel: RagLevel
  /**
   * Description
   */
  description: string
  /**
   * Severityhint
   */
  severityHint?: number | null
}

/**
 * ClientCreate
 */
export type ClientCreate = {
  /**
   * Companyname
   */
  companyName: string
  /**
   * Companieshousenumber
   */
  companiesHouseNumber?: string | null
  /**
   * Primarycontactname
   */
  primaryContactName: string
  /**
   * Primarycontactemail
   */
  primaryContactEmail: string
  /**
   * Primarycontactphone
   */
  primaryContactPhone?: string | null
  /**
   * Sector
   */
  sector?: string | null
  /**
   * Headcountatengagement
   */
  headcountAtEngagement: number
  /**
   * Currentheadcount
   */
  currentHeadcount?: number | null
  businessStage: BusinessStage
  region: UkRegion
  /**
   * Assignedoperatorid
   */
  assignedOperatorId: string
  /**
   * Internalnotes
   */
  internalNotes?: string | null
  /**
   * Introducerfeeapplicable
   */
  introducerFeeApplicable?: boolean | null
  status?: ClientStatus
}

/**
 * ClientRead
 */
export type ClientRead = {
  /**
   * Id
   */
  id: string
  /**
   * Companyname
   */
  companyName: string
  /**
   * Companieshousenumber
   */
  companiesHouseNumber: string | null
  /**
   * Primarycontactname
   */
  primaryContactName: string
  /**
   * Primarycontactemail
   */
  primaryContactEmail: string
  /**
   * Primarycontactphone
   */
  primaryContactPhone: string | null
  /**
   * Sector
   */
  sector: string | null
  /**
   * Headcountatengagement
   */
  headcountAtEngagement: number
  /**
   * Currentheadcount
   */
  currentHeadcount: number | null
  businessStage: BusinessStage
  region: UkRegion
  /**
   * Assignedoperatorid
   */
  assignedOperatorId: string | null
  /**
   * Internalnotes
   */
  internalNotes: string | null
  /**
   * Introducerfeeapplicable
   */
  introducerFeeApplicable: boolean | null
  status: ClientStatus
}

/**
 * ClientStatus
 */
export type ClientStatus =
  | 'ACTIVE'
  | 'AUDIT_IN_PROGRESS'
  | 'REPORT_ISSUED'
  | 'FOLLOW_UP_DUE'
  | 'INACTIVE'

/**
 * ClientUpdate
 */
export type ClientUpdate = {
  /**
   * Companyname
   */
  companyName: string
  /**
   * Companieshousenumber
   */
  companiesHouseNumber?: string | null
  /**
   * Primarycontactname
   */
  primaryContactName: string
  /**
   * Primarycontactemail
   */
  primaryContactEmail: string
  /**
   * Primarycontactphone
   */
  primaryContactPhone?: string | null
  /**
   * Sector
   */
  sector?: string | null
  /**
   * Headcountatengagement
   */
  headcountAtEngagement: number
  /**
   * Currentheadcount
   */
  currentHeadcount?: number | null
  businessStage: BusinessStage
  region: UkRegion
  /**
   * Assignedoperatorid
   */
  assignedOperatorId: string
  /**
   * Internalnotes
   */
  internalNotes?: string | null
  /**
   * Introducerfeeapplicable
   */
  introducerFeeApplicable?: boolean | null
  status: ClientStatus
}

/**
 * ControlTemplateCreate
 */
export type ControlTemplateCreate = {
  product: Product
  domain?: Domain | null
  /**
   * Code
   */
  code: string
  /**
   * Title
   */
  title: string
  /**
   * Whattesting
   */
  whatTesting: string
  /**
   * Whymatters
   */
  whyMatters: string
  /**
   * Primaryquestion
   */
  primaryQuestion: string
  /**
   * Evidenceprompts
   */
  evidencePrompts?: Array<string>
  /**
   * Lookingfor
   */
  lookingFor?: Array<string>
  /**
   * Sampling
   */
  sampling?: string | null
  /**
   * Ifpartial
   */
  ifPartial?: Array<string>
  /**
   * Sortorder
   */
  sortOrder?: number
  /**
   * Isactive
   */
  isActive?: boolean
  /**
   * Calibrationanchors
   */
  calibrationAnchors?: Array<CalibrationAnchorCreate>
}

/**
 * ControlTemplateRead
 */
export type ControlTemplateRead = {
  /**
   * Id
   */
  id: string
  product: Product
  domain: Domain | null
  /**
   * Code
   */
  code: string
  /**
   * Title
   */
  title: string
  /**
   * Whattesting
   */
  whatTesting: string
  /**
   * Whymatters
   */
  whyMatters: string
  /**
   * Primaryquestion
   */
  primaryQuestion: string
  /**
   * Evidenceprompts
   */
  evidencePrompts: Array<string>
  /**
   * Lookingfor
   */
  lookingFor: Array<string>
  /**
   * Sampling
   */
  sampling: string | null
  /**
   * Ifpartial
   */
  ifPartial: Array<string>
  /**
   * Sortorder
   */
  sortOrder: number
  /**
   * Isactive
   */
  isActive: boolean
  /**
   * Version
   */
  version: number
  /**
   * Createdat
   */
  createdAt: string
  /**
   * Updatedat
   */
  updatedAt: string
  /**
   * Calibrationanchors
   */
  calibrationAnchors?: Array<CalibrationAnchorRead>
}

/**
 * ControlTemplateUpdate
 */
export type ControlTemplateUpdate = {
  product: Product
  domain?: Domain | null
  /**
   * Code
   */
  code: string
  /**
   * Title
   */
  title: string
  /**
   * Whattesting
   */
  whatTesting: string
  /**
   * Whymatters
   */
  whyMatters: string
  /**
   * Primaryquestion
   */
  primaryQuestion: string
  /**
   * Evidenceprompts
   */
  evidencePrompts?: Array<string>
  /**
   * Lookingfor
   */
  lookingFor?: Array<string>
  /**
   * Sampling
   */
  sampling?: string | null
  /**
   * Ifpartial
   */
  ifPartial?: Array<string>
  /**
   * Sortorder
   */
  sortOrder?: number
  /**
   * Isactive
   */
  isActive?: boolean
  /**
   * Calibrationanchors
   */
  calibrationAnchors?: Array<CalibrationAnchorCreate> | null
}

/**
 * Domain
 */
export type Domain = 'A' | 'B' | 'C'

/**
 * EngagementCreate
 */
export type EngagementCreate = {
  product: Product
  /**
   * Engagementdate
   */
  engagementDate: string
  /**
   * Feecharged
   */
  feeCharged: number | string
  feeStatus: FeeStatus
  /**
   * Auditdate
   */
  auditDate?: string | null
  /**
   * Reportissueddate
   */
  reportIssuedDate?: string | null
  auditStatus?: AuditStatus
  /**
   * Nextreviewdue
   */
  nextReviewDue?: string | null
  /**
   * Engagementlettersignedat
   */
  engagementLetterSignedAt?: string | null
  /**
   * Invoiceraisedat
   */
  invoiceRaisedAt?: string | null
}

export type EngagementRead = {
  [key: string]: unknown
}

/**
 * EngagementUpdate
 */
export type EngagementUpdate = {
  product: Product
  /**
   * Engagementdate
   */
  engagementDate: string
  /**
   * Feecharged
   */
  feeCharged: number | string
  feeStatus: FeeStatus
  /**
   * Auditdate
   */
  auditDate?: string | null
  /**
   * Reportissueddate
   */
  reportIssuedDate?: string | null
  auditStatus?: AuditStatus
  /**
   * Nextreviewdue
   */
  nextReviewDue?: string | null
  /**
   * Engagementlettersignedat
   */
  engagementLetterSignedAt?: string | null
  /**
   * Invoiceraisedat
   */
  invoiceRaisedAt?: string | null
}

/**
 * FeeStatus
 */
export type FeeStatus = 'INVOICED' | 'PAID' | 'OVERDUE'

/**
 * GateCheckRead
 */
export type GateCheckRead = {
  /**
   * Id
   */
  id: string
  /**
   * Assessmentid
   */
  assessmentId: string | null
  /**
   * Engagementid
   */
  engagementId: string
  gate: GateName
  /**
   * Passed
   */
  passed: boolean
  /**
   * Reason
   */
  reason: string | null
  /**
   * Checkedat
   */
  checkedAt: string
  /**
   * Actorid
   */
  actorId: string | null
}

/**
 * GateName
 *
 * The seven hard gates from PRODUCT_SPEC §Hard Gates.
 */
export type GateName =
  | 'ENGAGEMENT_LETTER_SIGNED'
  | 'INVOICE_RAISED'
  | 'NO_RAG_DURING_PHASE_1'
  | 'PHASE_1_CLOSED'
  | 'PHASE_2_MANDATORY_FIELDS_COMPLETE'
  | 'QA_SIGN_OFF'
  | 'ADMIN_REPORT_REVIEW'

/**
 * GateReport
 */
export type GateReport = {
  /**
   * Engagementid
   */
  engagementId: string
  /**
   * Assessmentid
   */
  assessmentId: string | null
  /**
   * Gates
   */
  gates: Array<GateStatus>
}

/**
 * GateStatus
 */
export type GateStatus = {
  gate: GateName
  /**
   * Passed
   */
  passed: boolean
  /**
   * Reason
   */
  reason?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
}

/**
 * NoDataResponse
 */
export type NoDataResponse = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
}

/**
 * PermissionRead
 */
export type PermissionRead = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string | null
}

/**
 * Product
 */
export type Product =
  | 'HIRE_READY'
  | 'THE_CHECK'
  | 'HIRE_3D_CORE'
  | 'HIRE_3D_ENHANCED'

/**
 * RAGLevel
 */
export type RagLevel = 'RED' | 'AMBER_RED' | 'AMBER' | 'GREEN_AMBER' | 'GREEN'

/**
 * Response[AccessTokenResponse]
 */
export type ResponseAccessTokenResponse = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: AccessTokenResponse
}

/**
 * Response[AssessmentRead]
 */
export type ResponseAssessmentRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: AssessmentRead
}

/**
 * Response[AuditLogPage]
 */
export type ResponseAuditLogPage = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: AuditLogPage
}

/**
 * Response[CalibrationAnchorRead]
 */
export type ResponseCalibrationAnchorRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: CalibrationAnchorRead
}

/**
 * Response[ClientRead]
 */
export type ResponseClientRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: ClientRead
}

/**
 * Response[ControlTemplateRead]
 */
export type ResponseControlTemplateRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: ControlTemplateRead
}

/**
 * Response[EngagementRead]
 */
export type ResponseEngagementRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: EngagementRead
}

/**
 * Response[GateReport]
 */
export type ResponseGateReport = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: GateReport
}

/**
 * Response[RoleRead]
 */
export type ResponseRoleRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: RoleRead
}

/**
 * Response[TOTPSetupResponse]
 */
export type ResponseTotpSetupResponse = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: TotpSetupResponse
}

/**
 * Response[TokenResponse]
 */
export type ResponseTokenResponse = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: TokenResponse
}

/**
 * Response[Union[AssessmentRead, NoneType]]
 */
export type ResponseUnionAssessmentReadNoneType = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: AssessmentRead | null
}

/**
 * Response[Union[TokenResponse, TOTPChallengeResponse]]
 */
export type ResponseUnionTokenResponseTotpChallengeResponse = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: TokenResponse | TotpChallengeResponse
}

/**
 * Response[UserRead]
 */
export type ResponseUserRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  data: UserRead
}

/**
 * Response[list[ClientRead]]
 */
export type ResponseListClientRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: Array<ClientRead>
}

/**
 * Response[list[ControlTemplateRead]]
 */
export type ResponseListControlTemplateRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: Array<ControlTemplateRead>
}

/**
 * Response[list[EngagementRead]]
 */
export type ResponseListEngagementRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: Array<EngagementRead>
}

/**
 * Response[list[GateCheckRead]]
 */
export type ResponseListGateCheckRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: Array<GateCheckRead>
}

/**
 * Response[list[RoleRead]]
 */
export type ResponseListRoleRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: Array<RoleRead>
}

/**
 * Response[list[UserRead]]
 */
export type ResponseListUserRead = {
  /**
   * Message
   *
   * A message describing the result of the operation.
   */
  message?: string
  /**
   * Success
   *
   * Indicates whether the operation was successful.
   */
  success?: boolean
  /**
   * Data
   */
  data: Array<UserRead>
}

/**
 * RiskRating
 */
export type RiskRating = 'RED' | 'AMBER_RED' | 'AMBER' | 'GREEN_AMBER' | 'GREEN'

/**
 * RoleCreate
 */
export type RoleCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Permissions
   */
  permissions?: Array<string>
}

/**
 * RoleRead
 */
export type RoleRead = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string | null
  /**
   * Issystem
   */
  isSystem: boolean
  /**
   * Permissions
   */
  permissions: Array<PermissionRead>
}

/**
 * RoleUpdate
 */
export type RoleUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Permissions
   */
  permissions?: Array<string> | null
}

/**
 * TOTPChallengeResponse
 */
export type TotpChallengeResponse = {
  /**
   * Requires2Fa
   */
  requires2Fa?: true
  /**
   * Totptoken
   */
  totpToken: string
}

/**
 * TOTPConfirmRequest
 */
export type TotpConfirmRequest = {
  /**
   * Totptoken
   */
  totpToken: string
  /**
   * Code
   */
  code: string
}

/**
 * TOTPSetupResponse
 */
export type TotpSetupResponse = {
  /**
   * Qruri
   */
  qrUri: string
  /**
   * Issuer
   */
  issuer: string
}

/**
 * TOTPVerifyRequest
 */
export type TotpVerifyRequest = {
  /**
   * Code
   */
  code: string
}

/**
 * TokenResponse
 */
export type TokenResponse = {
  /**
   * Requires2Fa
   */
  requires2Fa?: false
  /**
   * Accesstoken
   */
  accessToken: string
  /**
   * Tokentype
   */
  tokenType?: string
}

/**
 * UKRegion
 */
export type UkRegion =
  | 'EAST_MIDLANDS'
  | 'EAST_OF_ENGLAND'
  | 'LONDON'
  | 'NORTH_EAST'
  | 'NORTH_WEST'
  | 'SOUTH_EAST'
  | 'SOUTH_WEST'
  | 'WEST_MIDLANDS'
  | 'YORKSHIRE_AND_THE_HUMBER'
  | 'NORTHERN_IRELAND'
  | 'SCOTLAND'
  | 'WALES'

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
  /**
   * Role
   */
  role?: string | null
  status?: UserStatus | null
}

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Email
   */
  email: string
  /**
   * Role
   */
  role: string | null
  status: UserStatus
}

/**
 * UserStatus
 */
export type UserStatus = 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'SUSPENDED'

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Role
   */
  role?: string | null
  status?: UserStatus | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type LoginData = {
  body: LoginRequest
  path?: never
  query?: never
  url: '/api/v1/auth/login'
}

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginError = LoginErrors[keyof LoginErrors]

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: ResponseUnionTokenResponseTotpChallengeResponse
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type RefreshData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/refresh'
}

export type RefreshResponses = {
  /**
   * Successful Response
   */
  200: ResponseAccessTokenResponse
}

export type RefreshResponse = RefreshResponses[keyof RefreshResponses]

export type LogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/logout'
}

export type LogoutResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type LogoutResponse = LogoutResponses[keyof LogoutResponses]

export type TotpSetupData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/totp/setup'
}

export type TotpSetupResponses = {
  /**
   * Successful Response
   */
  200: ResponseTotpSetupResponse
}

export type TotpSetupResponse2 = TotpSetupResponses[keyof TotpSetupResponses]

export type TotpDisableData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/auth/totp'
}

export type TotpDisableResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type TotpDisableResponse =
  TotpDisableResponses[keyof TotpDisableResponses]

export type TotpVerifyData = {
  body: TotpVerifyRequest
  path?: never
  query?: never
  url: '/api/v1/auth/totp/verify'
}

export type TotpVerifyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TotpVerifyError = TotpVerifyErrors[keyof TotpVerifyErrors]

export type TotpVerifyResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type TotpVerifyResponse = TotpVerifyResponses[keyof TotpVerifyResponses]

export type RevokeSessionsData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/auth/sessions/{user_id}'
}

export type RevokeSessionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RevokeSessionsError =
  RevokeSessionsErrors[keyof RevokeSessionsErrors]

export type RevokeSessionsResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type RevokeSessionsResponse =
  RevokeSessionsResponses[keyof RevokeSessionsResponses]

export type TotpConfirmData = {
  body: TotpConfirmRequest
  path?: never
  query?: never
  url: '/api/v1/auth/totp/confirm'
}

export type TotpConfirmErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TotpConfirmError = TotpConfirmErrors[keyof TotpConfirmErrors]

export type TotpConfirmResponses = {
  /**
   * Successful Response
   */
  200: ResponseTokenResponse
}

export type TotpConfirmResponse =
  TotpConfirmResponses[keyof TotpConfirmResponses]

export type ListUsersData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users'
}

export type ListUsersResponses = {
  /**
   * Successful Response
   */
  200: ResponseListUserRead
}

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses]

export type CreateUserData = {
  body: UserCreate
  path?: never
  query?: never
  url: '/api/v1/users'
}

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors]

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  201: ResponseUserRead
}

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses]

export type DeactivateUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type DeactivateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeactivateUserError =
  DeactivateUserErrors[keyof DeactivateUserErrors]

export type DeactivateUserResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type DeactivateUserResponse =
  DeactivateUserResponses[keyof DeactivateUserResponses]

export type GetUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type GetUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetUserError = GetUserErrors[keyof GetUserErrors]

export type GetUserResponses = {
  /**
   * Successful Response
   */
  200: ResponseUserRead
}

export type GetUserResponse = GetUserResponses[keyof GetUserResponses]

export type UpdateUserData = {
  body: UserUpdate
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors]

export type UpdateUserResponses = {
  /**
   * Successful Response
   */
  200: ResponseUserRead
}

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses]

export type ListRolesData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/roles'
}

export type ListRolesResponses = {
  /**
   * Successful Response
   */
  200: ResponseListRoleRead
}

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses]

export type CreateRoleData = {
  body: RoleCreate
  path?: never
  query?: never
  url: '/api/v1/roles'
}

export type CreateRoleErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors]

export type CreateRoleResponses = {
  /**
   * Successful Response
   */
  201: ResponseRoleRead
}

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses]

export type DeleteRoleData = {
  body?: never
  path: {
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/v1/roles/{role_id}'
}

export type DeleteRoleErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors]

export type DeleteRoleResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses]

export type UpdateRoleData = {
  body: RoleUpdate
  path: {
    /**
     * Role Id
     */
    role_id: string
  }
  query?: never
  url: '/api/v1/roles/{role_id}'
}

export type UpdateRoleErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors]

export type UpdateRoleResponses = {
  /**
   * Successful Response
   */
  200: ResponseRoleRead
}

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses]

export type ListClientsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/clients'
}

export type ListClientsResponses = {
  /**
   * Successful Response
   */
  200: ResponseListClientRead
}

export type ListClientsResponse =
  ListClientsResponses[keyof ListClientsResponses]

export type CreateClientData = {
  body: ClientCreate
  path?: never
  query?: never
  url: '/api/v1/clients'
}

export type CreateClientErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateClientError = CreateClientErrors[keyof CreateClientErrors]

export type CreateClientResponses = {
  /**
   * Successful Response
   */
  201: ResponseClientRead
}

export type CreateClientResponse =
  CreateClientResponses[keyof CreateClientResponses]

export type DeleteClientData = {
  body?: never
  path: {
    /**
     * Client Id
     */
    client_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}'
}

export type DeleteClientErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteClientError = DeleteClientErrors[keyof DeleteClientErrors]

export type DeleteClientResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type DeleteClientResponse =
  DeleteClientResponses[keyof DeleteClientResponses]

export type GetClientData = {
  body?: never
  path: {
    /**
     * Client Id
     */
    client_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}'
}

export type GetClientErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetClientError = GetClientErrors[keyof GetClientErrors]

export type GetClientResponses = {
  /**
   * Successful Response
   */
  200: ResponseClientRead
}

export type GetClientResponse = GetClientResponses[keyof GetClientResponses]

export type UpdateClientData = {
  body: ClientUpdate
  path: {
    /**
     * Client Id
     */
    client_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}'
}

export type UpdateClientErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateClientError = UpdateClientErrors[keyof UpdateClientErrors]

export type UpdateClientResponses = {
  /**
   * Successful Response
   */
  200: ResponseClientRead
}

export type UpdateClientResponse =
  UpdateClientResponses[keyof UpdateClientResponses]

export type ListEngagementsData = {
  body?: never
  path: {
    /**
     * Client Id
     */
    client_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}/engagements'
}

export type ListEngagementsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListEngagementsError =
  ListEngagementsErrors[keyof ListEngagementsErrors]

export type ListEngagementsResponses = {
  /**
   * Successful Response
   */
  200: ResponseListEngagementRead
}

export type ListEngagementsResponse =
  ListEngagementsResponses[keyof ListEngagementsResponses]

export type CreateEngagementData = {
  body: EngagementCreate
  path: {
    /**
     * Client Id
     */
    client_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}/engagements'
}

export type CreateEngagementErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateEngagementError =
  CreateEngagementErrors[keyof CreateEngagementErrors]

export type CreateEngagementResponses = {
  /**
   * Successful Response
   */
  201: ResponseEngagementRead
}

export type CreateEngagementResponse =
  CreateEngagementResponses[keyof CreateEngagementResponses]

export type DeleteEngagementData = {
  body?: never
  path: {
    /**
     * Client Id
     */
    client_id: string
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}/engagements/{engagement_id}'
}

export type DeleteEngagementErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteEngagementError =
  DeleteEngagementErrors[keyof DeleteEngagementErrors]

export type DeleteEngagementResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type DeleteEngagementResponse =
  DeleteEngagementResponses[keyof DeleteEngagementResponses]

export type GetEngagementData = {
  body?: never
  path: {
    /**
     * Client Id
     */
    client_id: string
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}/engagements/{engagement_id}'
}

export type GetEngagementErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetEngagementError = GetEngagementErrors[keyof GetEngagementErrors]

export type GetEngagementResponses = {
  /**
   * Successful Response
   */
  200: ResponseEngagementRead
}

export type GetEngagementResponse =
  GetEngagementResponses[keyof GetEngagementResponses]

export type UpdateEngagementData = {
  body: EngagementUpdate
  path: {
    /**
     * Client Id
     */
    client_id: string
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/clients/{client_id}/engagements/{engagement_id}'
}

export type UpdateEngagementErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateEngagementError =
  UpdateEngagementErrors[keyof UpdateEngagementErrors]

export type UpdateEngagementResponses = {
  /**
   * Successful Response
   */
  200: ResponseEngagementRead
}

export type UpdateEngagementResponse =
  UpdateEngagementResponses[keyof UpdateEngagementResponses]

export type ListControlTemplatesData = {
  body?: never
  path?: never
  query?: {
    /**
     * Product
     */
    product?: Product | null
    /**
     * Domain
     */
    domain?: Domain | null
    /**
     * Activeonly
     */
    activeOnly?: boolean
  }
  url: '/api/v1/control-templates'
}

export type ListControlTemplatesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListControlTemplatesError =
  ListControlTemplatesErrors[keyof ListControlTemplatesErrors]

export type ListControlTemplatesResponses = {
  /**
   * Successful Response
   */
  200: ResponseListControlTemplateRead
}

export type ListControlTemplatesResponse =
  ListControlTemplatesResponses[keyof ListControlTemplatesResponses]

export type CreateControlTemplateData = {
  body: ControlTemplateCreate
  path?: never
  query?: never
  url: '/api/v1/control-templates'
}

export type CreateControlTemplateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateControlTemplateError =
  CreateControlTemplateErrors[keyof CreateControlTemplateErrors]

export type CreateControlTemplateResponses = {
  /**
   * Successful Response
   */
  201: ResponseControlTemplateRead
}

export type CreateControlTemplateResponse =
  CreateControlTemplateResponses[keyof CreateControlTemplateResponses]

export type DeleteControlTemplateData = {
  body?: never
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/api/v1/control-templates/{template_id}'
}

export type DeleteControlTemplateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteControlTemplateError =
  DeleteControlTemplateErrors[keyof DeleteControlTemplateErrors]

export type DeleteControlTemplateResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type DeleteControlTemplateResponse =
  DeleteControlTemplateResponses[keyof DeleteControlTemplateResponses]

export type GetControlTemplateData = {
  body?: never
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/api/v1/control-templates/{template_id}'
}

export type GetControlTemplateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetControlTemplateError =
  GetControlTemplateErrors[keyof GetControlTemplateErrors]

export type GetControlTemplateResponses = {
  /**
   * Successful Response
   */
  200: ResponseControlTemplateRead
}

export type GetControlTemplateResponse =
  GetControlTemplateResponses[keyof GetControlTemplateResponses]

export type UpdateControlTemplateData = {
  body: ControlTemplateUpdate
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/api/v1/control-templates/{template_id}'
}

export type UpdateControlTemplateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateControlTemplateError =
  UpdateControlTemplateErrors[keyof UpdateControlTemplateErrors]

export type UpdateControlTemplateResponses = {
  /**
   * Successful Response
   */
  200: ResponseControlTemplateRead
}

export type UpdateControlTemplateResponse =
  UpdateControlTemplateResponses[keyof UpdateControlTemplateResponses]

export type UpsertCalibrationAnchorData = {
  body: CalibrationAnchorCreate
  path: {
    /**
     * Template Id
     */
    template_id: string
  }
  query?: never
  url: '/api/v1/control-templates/{template_id}/calibration-anchors'
}

export type UpsertCalibrationAnchorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpsertCalibrationAnchorError =
  UpsertCalibrationAnchorErrors[keyof UpsertCalibrationAnchorErrors]

export type UpsertCalibrationAnchorResponses = {
  /**
   * Successful Response
   */
  200: ResponseCalibrationAnchorRead
}

export type UpsertCalibrationAnchorResponse =
  UpsertCalibrationAnchorResponses[keyof UpsertCalibrationAnchorResponses]

export type DeleteCalibrationAnchorData = {
  body?: never
  path: {
    /**
     * Anchor Id
     */
    anchor_id: string
  }
  query?: never
  url: '/api/v1/calibration-anchors/{anchor_id}'
}

export type DeleteCalibrationAnchorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteCalibrationAnchorError =
  DeleteCalibrationAnchorErrors[keyof DeleteCalibrationAnchorErrors]

export type DeleteCalibrationAnchorResponses = {
  /**
   * Successful Response
   */
  200: NoDataResponse
}

export type DeleteCalibrationAnchorResponse =
  DeleteCalibrationAnchorResponses[keyof DeleteCalibrationAnchorResponses]

export type UpdateCalibrationAnchorData = {
  body: CalibrationAnchorUpdate
  path: {
    /**
     * Anchor Id
     */
    anchor_id: string
  }
  query?: never
  url: '/api/v1/calibration-anchors/{anchor_id}'
}

export type UpdateCalibrationAnchorErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateCalibrationAnchorError =
  UpdateCalibrationAnchorErrors[keyof UpdateCalibrationAnchorErrors]

export type UpdateCalibrationAnchorResponses = {
  /**
   * Successful Response
   */
  200: ResponseCalibrationAnchorRead
}

export type UpdateCalibrationAnchorResponse =
  UpdateCalibrationAnchorResponses[keyof UpdateCalibrationAnchorResponses]

export type GetEngagementGatesData = {
  body?: never
  path: {
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/engagements/{engagement_id}/gates'
}

export type GetEngagementGatesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetEngagementGatesError =
  GetEngagementGatesErrors[keyof GetEngagementGatesErrors]

export type GetEngagementGatesResponses = {
  /**
   * Successful Response
   */
  200: ResponseGateReport
}

export type GetEngagementGatesResponse =
  GetEngagementGatesResponses[keyof GetEngagementGatesResponses]

export type GetEngagementAssessmentData = {
  body?: never
  path: {
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/engagements/{engagement_id}/assessment'
}

export type GetEngagementAssessmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetEngagementAssessmentError =
  GetEngagementAssessmentErrors[keyof GetEngagementAssessmentErrors]

export type GetEngagementAssessmentResponses = {
  /**
   * Successful Response
   */
  200: ResponseUnionAssessmentReadNoneType
}

export type GetEngagementAssessmentResponse =
  GetEngagementAssessmentResponses[keyof GetEngagementAssessmentResponses]

export type StartAssessmentData = {
  body?: never
  path: {
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/engagements/{engagement_id}/assessment/start'
}

export type StartAssessmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type StartAssessmentError =
  StartAssessmentErrors[keyof StartAssessmentErrors]

export type StartAssessmentResponses = {
  /**
   * Successful Response
   */
  201: ResponseAssessmentRead
}

export type StartAssessmentResponse =
  StartAssessmentResponses[keyof StartAssessmentResponses]

export type CloseAssessmentPhase1Data = {
  body?: never
  path: {
    /**
     * Assessment Id
     */
    assessment_id: string
  }
  query?: never
  url: '/api/v1/assessments/{assessment_id}/close-phase-1'
}

export type CloseAssessmentPhase1Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CloseAssessmentPhase1Error =
  CloseAssessmentPhase1Errors[keyof CloseAssessmentPhase1Errors]

export type CloseAssessmentPhase1Responses = {
  /**
   * Successful Response
   */
  200: ResponseAssessmentRead
}

export type CloseAssessmentPhase1Response =
  CloseAssessmentPhase1Responses[keyof CloseAssessmentPhase1Responses]

export type SubmitAssessmentPhase2Data = {
  body?: never
  path: {
    /**
     * Assessment Id
     */
    assessment_id: string
  }
  query?: never
  url: '/api/v1/assessments/{assessment_id}/submit-phase-2'
}

export type SubmitAssessmentPhase2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SubmitAssessmentPhase2Error =
  SubmitAssessmentPhase2Errors[keyof SubmitAssessmentPhase2Errors]

export type SubmitAssessmentPhase2Responses = {
  /**
   * Successful Response
   */
  200: ResponseAssessmentRead
}

export type SubmitAssessmentPhase2Response =
  SubmitAssessmentPhase2Responses[keyof SubmitAssessmentPhase2Responses]

export type CancelAssessmentData = {
  body?: never
  path: {
    /**
     * Assessment Id
     */
    assessment_id: string
  }
  query?: never
  url: '/api/v1/assessments/{assessment_id}/cancel'
}

export type CancelAssessmentErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CancelAssessmentError =
  CancelAssessmentErrors[keyof CancelAssessmentErrors]

export type CancelAssessmentResponses = {
  /**
   * Successful Response
   */
  200: ResponseAssessmentRead
}

export type CancelAssessmentResponse =
  CancelAssessmentResponses[keyof CancelAssessmentResponses]

export type ListGateChecksData = {
  body?: never
  path: {
    /**
     * Engagement Id
     */
    engagement_id: string
  }
  query?: never
  url: '/api/v1/engagements/{engagement_id}/gate-checks'
}

export type ListGateChecksErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListGateChecksError =
  ListGateChecksErrors[keyof ListGateChecksErrors]

export type ListGateChecksResponses = {
  /**
   * Successful Response
   */
  200: ResponseListGateCheckRead
}

export type ListGateChecksResponse =
  ListGateChecksResponses[keyof ListGateChecksResponses]

export type ListAuditLogsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Limit
     */
    limit?: number
    /**
     * Offset
     */
    offset?: number
    /**
     * Action
     */
    action?: AuditAction | null
    /**
     * Resource Type
     */
    resource_type?: string | null
    /**
     * Actor Id
     */
    actor_id?: string | null
    /**
     * Before
     */
    before?: string | null
    /**
     * After
     */
    after?: string | null
  }
  url: '/api/v1/audit-logs'
}

export type ListAuditLogsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListAuditLogsError = ListAuditLogsErrors[keyof ListAuditLogsErrors]

export type ListAuditLogsResponses = {
  /**
   * Successful Response
   */
  200: ResponseAuditLogPage
}

export type ListAuditLogsResponse =
  ListAuditLogsResponses[keyof ListAuditLogsResponses]
